ODR\AdminBundle\Entity\UserPermissions:
    type: entity
    table: odr_user_permissions
    gedmo:
#        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        can_view_type:
            type: integer
            unsigned: false
            nullable: false
            default: 0

        can_edit_record:
            type: integer
            unsigned: false
            nullable: false
            default: 0
        can_add_record:
            type: integer
            unsigned: false
            nullable: false
            default: 0
        can_delete_record:
            type: integer
            unsigned: false
            nullable: false
            default: 0

        can_design_type:
            type: integer
            unsigned: false
            nullable: false
            default: 0
        is_type_admin:
            type: integer
            unsigned: false
            nullable: false
            default: 0

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: datetime
            nullable: true
#            gedmo:
#                - versioned

    manyToOne:
        user:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        dataType:
            targetEntity: DataType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                data_type_id:
                    referencedColumnName: id
            orphanRemoval: false
        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
